/**
 * Pins the TypeScript port in src/egp to the Python reference implementation
 * in ../egp. golden.json is regenerated by scripts/make_golden.py; the
 * special functions and closed forms must match to near machine precision,
 * while the particle filter (whose RNG necessarily differs) must agree
 * statistically and satisfy the exact white-noise and bounds identities.
 */
import { describe, expect, it } from 'vitest'
import golden from '../golden.json'
import { logNdtr, ndtriExp } from '../src/egp/normal'
import { logCellProb, particleFilterLoglik } from '../src/egp/pf'
import { minimumPhaseFromTaps } from '../src/egp/factor'
import { entropyRateApprox } from '../src/egp/approx'
import { fineQuantizationBits, marginalEntropyBits } from '../src/egp/bounds'
import { generateQuantized, replicateSeed } from '../src/egp/process'
import { Rng } from '../src/egp/rng'
import { designKernel, DEFAULT_SPEC } from '../src/model/filters'

const KERNELS: Record<string, Float64Array> = {
  white: new Float64Array([1]),
  ma8: new Float64Array(8).fill(1 / 8),
  diff: new Float64Array([1, -1]),
  lowpass_6k_30k_65: designKernel({ ...DEFAULT_SPEC, family: 'lowpass', highHz: 6000, taps: 65 }, 30000),
  bandpass_300_6000_30k_101: designKernel(
    { ...DEFAULT_SPEC, family: 'bandpass', lowHz: 300, highHz: 6000, taps: 101 },
    30000,
  ),
}

function relClose(actual: number, expected: number, rel: number, abs = 0) {
  expect(Math.abs(actual - expected)).toBeLessThanOrEqual(rel * Math.abs(expected) + abs)
}

describe('normal special functions vs scipy', () => {
  it('logNdtr matches log_ndtr', () => {
    for (const [x, want] of Object.entries(golden.logNdtr)) {
      relClose(logNdtr(Number(x)), want as number, 1e-12, 1e-13)
    }
  })

  it('ndtriExp matches ndtri_exp', () => {
    for (const [y, want] of Object.entries(golden.ndtriExp)) {
      relClose(ndtriExp(Number(y)), want as number, 1e-9, 1e-12)
    }
  })

  it('logCellProb matches log_cell_prob', () => {
    for (const [key, want] of Object.entries(golden.logCellProb)) {
      const [lo, hi] = key.split(',').map(Number)
      relClose(logCellProb(lo, hi), want as number, 1e-11, 1e-12)
    }
  })
})

describe('factorization, approximation and bounds vs egp', () => {
  // Sharp filters have deep stopbands where the spectrum is catastrophic-
  // cancellation noise at the 1e-14 floor; the exact taps there differ
  // between FFT implementations while h0 and the autocovariance — the process
  // law, which is what the paper says to verify — are robust.
  const SHARP = new Set(['lowpass_6k_30k_65', 'bandpass_300_6000_30k_101'])

  for (const [name, g] of Object.entries(golden.kernels)) {
    it(name, () => {
      const kernel = KERNELS[name]
      expect(kernel).toBeDefined()
      const taps = Float64Array.from(kernel, v => g.sigma * v)
      const fac = minimumPhaseFromTaps(taps)

      // Sharp filters: h0 depends on log S across the floored stopband, where
      // the spectrum is FFT rounding noise, and the factorization itself is
      // ill-conditioned near unit-circle zeros — so taps and h0 agree with
      // Python only to ~1e-2·h0 while both reproduce the process law (the
      // autocovariance, the check the paper prescribes) to ~1e-10.
      relClose(fac.h0, g.h0, SHARP.has(name) ? 1e-2 : 1e-6)
      const tapAbs = (SHARP.has(name) ? 0.1 : 1e-8) * fac.h0
      for (let i = 0; i < g.minPhaseHead.length && i < fac.taps.length; i++) {
        relClose(fac.taps[i], g.minPhaseHead[i], SHARP.has(name) ? 0 : 1e-5, tapAbs)
      }
      // The check that matters: the factor reproduces the target process law.
      expect(fac.autocovError).toBeLessThanOrEqual(Math.max(2 * g.autocovError, 1e-8))
      relClose(entropyRateApprox(taps, 1), g.approxBits, 1e-9, 1e-9)
      relClose(Math.max(0, fineQuantizationBits(fac.h0, 1)), g.lowerBoundBits, SHARP.has(name) ? 1e-2 : 1e-6, 1e-9)

      let energy = 0
      for (const v of taps) energy += v * v
      relClose(Math.sqrt(energy), g.sigmaY, 1e-12)
      relClose(marginalEntropyBits(Math.sqrt(energy), 1), g.upperBoundBits, 1e-9, 1e-10)
    })
  }
})

describe('particle filter', () => {
  it('white noise: the filter is exact and lands on H(Y_1)', { timeout: 60_000 }, () => {
    const taps = new Float64Array([5])
    const rng = new Rng(replicateSeed(1234, 0))
    const y = generateQuantized(taps, 100_000, 1, rng)
    const result = particleFilterLoglik(y, taps, 1, 10, rng)
    // The estimator equals the exact plug-in likelihood; only the finite-n
    // SMB fluctuation separates it from H(Y_1).
    relClose(result.entropyRateBits, golden.kernels.white.upperBoundBits, 0, 0.05)
    expect(result.lostLockFraction).toBe(0)
  })

  it('MA(8) at sigma 5 agrees with the Python reference statistically', { timeout: 300_000 }, () => {
    const g = golden.pfReference
    const taps = minimumPhaseFromTaps(Float64Array.from(KERNELS.ma8, v => 5 * v)).taps
    const values: number[] = []
    let essSum = 0
    for (let rep = 0; rep < 2; rep++) {
      const rng = new Rng(replicateSeed(777, rep))
      const y = generateQuantized(taps, g.n, 1, rng)
      const result = particleFilterLoglik(y, taps, 1, g.nParticles, rng)
      values.push(result.entropyRateBits)
      essSum += result.meanEss
      expect(result.lostLockFraction).toBeLessThan(1e-3)
    }
    const mean = (values[0] + values[1]) / 2
    // Different RNGs: agreement is statistical. Replicate sd is ~0.008 bits at
    // this n, so 0.03 is a ~5 sigma envelope around the Python mean.
    relClose(mean, g.meanBits, 0, 0.03)
    // ESS is a property of the model, not the RNG; it should reproduce closely.
    relClose(essSum / 2, g.meanEss, 0.05)
    // The estimate must respect the rigorous bracket.
    expect(mean).toBeGreaterThan(golden.kernels.ma8.lowerBoundBits)
    expect(mean).toBeLessThan(golden.kernels.ma8.upperBoundBits)
    // ... and sit near the spectral approximation (paper: within ~0.1 bit).
    relClose(mean, golden.kernels.ma8.approxBits, 0, 0.1)
  })
})
